name: MLOps Pipeline

on:
  push:
    branches: [ master ]   # master 브랜치 사용 시
  pull_request:
    branches: [ master ]

jobs:
  mlops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect weather data
        run: python main.py collect_weather --years=5

      - name: Split data
        run: python main.py split_data --csv_name=tokyo_weather.csv --test_size=0.2

      - name: Train Prophet model
        run: python main.py train_prophet --train_csv=dataset/train.csv --seasonality_mode=additive --changepoint_prior_scale=0.05

      - name: Evaluate Prophet model
        run: python main.py evaluate_prophet --model_path=models/prophet_model.pkl --test_csv=dataset/test.csv

      - name: Predict future
        run: python main.py predict_future --model_path=models/prophet_model.pkl --last_date=2024-05-29 --days=7

      - name: Recommend clothing
        run: python main.py recommend_clothing --future_csv=future_temperature.csv
